seferov_blog_blog:
    resource: "@SeferovBlogBundle/Resources/config/routing/blog.yml"

seferov_blog_admin:
    prefix:   /admin
    resource: "@SeferovBlogBundle/Resources/config/routing/admin.yml"
